name: 'Sanitize Branch Name'
description: 'Determine & Sanitize branch name of any special characters, for use in artifact upload actions'
outputs:
  branch-name:
    description: "Determined branch name"
    value: ${{ steps.determine_branch.outputs.branch_name }}
  sanitized-branch-name:
    description: "Determined branch name without any forward slashes"
    value: ${{ steps.sanitize_branch.outputs.sanitized_branch_name }}    
runs:
  using: "composite"
  steps:
    - name: "Determine Branch"
      id: determine_branch
      shell: bash
      run: |
        BRANCH=${{ github.head_ref }}
        if [ "$BRANCH" == "" ]; then
            BRANCH=$(echo ${{ github.ref }} | sed 's/refs\/heads\///');
        fi;
        echo "Determined branch: $BRANCH"
        echo "branch_name=$BRANCH" >> $GITHUB_OUTPUT;

    - name: "Sanitize Branch name"
      id: sanitize_branch
      shell: bash
      run: |
        SANITIZED_BRANCH_NAME=$(echo -n ${{ steps.determine_branch.outputs.branch_name }} | tr "/" "-")
        echo "Sanitized branch name: $SANITIZED_BRANCH_NAME"
        echo "sanitized_branch_name=$SANITIZED_BRANCH_NAME" >> $GITHUB_OUTPUT;

